name: Build saphi

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-saphi-server-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: build
        run: (cd Saphi/Server && make server)
      - name: compress
        run: tar -f SaphiServer-linux-x64.tar.gz -c Server
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: SaphiServer-linux-x64.tar.gz
  build-saphi-client-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: install sdl
        run: sudo apt install libsdl2-dev
      - name: build
        run: (cd Saphi/Client && make duck)
      - name: compress
        run: tar -f SaphiClient-duck-linux-x64.tar.gz -c Client
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: SaphiClient-duck-linux-x64.tar.gz
